[connections.car_db]
dialect = "mysql" # 접속할 데이터베이스 종류
username = "root" # 접속할 데이터베이스 계정
password = "root1234" # 접속할 데이터베이스 비밀번호
host = "localhost" # 접속할 데이터베이스 주소
database = "car_registration_status" # 접속할 데이터베이스 이름